// Code generated by protoc-gen-gomeet-service. DO NOT EDIT.
// source: pb/api-gateway.proto
package service

import (
	pb "github.com/gomeet-examples/svc-api-gateway/pb"
	// SUB-SERVICES DEFINITION : import-pb
	// svc{{SubServiceNamePascalCase}}Pb "github.com/gomeet-examples/svc-{{SubServiceNameKebabCase}}/pb"
	svcEchoPb "github.com/gomeet-examples/svc-echo/pb"
	svcProfilePb "github.com/gomeet-examples/svc-profile/pb"
	// END SUB-SERVICES DEFINITION : import-pb
)

// Implements of apiGatewayServer
type apiGatewayServer struct {
	jwtSecret     string
	caCertificate string
	certificate   string
	privateKey    string

	// EXTRA : var
	// END EXTRA : var

	// SUB-SERVICES DEFINITION : var-address
	// svc{{SubServiceNamePascalCase}}Address string
	svcEchoAddress    string
	svcProfileAddress string
	// END SUB-SERVICES DEFINITION : var-address

	// SUB-SERVICES DEFINITION : var-client
	// svc{{SubServiceNamePascalCase}}GrpcClient svc{{SubServiceNamePascalCase}}Pb.{{SubServiceNamePascalCase}}Client
	svcEchoGrpcClient    svcEchoPb.EchoClient
	svcProfileGrpcClient svcProfilePb.ProfileClient
	// END SUB-SERVICES DEFINITION : var-client
}

func newApiGatewayServer() pb.ApiGatewayServer {
	return new(apiGatewayServer)
}
