// Code generated by protoc-gen-gomeet-service. DO NOT EDIT.
// source: pb/api-gateway.proto
// to extend the apiGatewayHTTPController struct use a new file
package service

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"

	log "github.com/sirupsen/logrus"

	pb "github.com/gomeet-examples/svc-api-gateway/pb"
)

type apiGatewayHTTPController struct{}

func newApiGatewayHTTPController() *apiGatewayHTTPController {
	return new(apiGatewayHTTPController)
}

func (s apiGatewayHTTPController) Status(w http.ResponseWriter, r *http.Request) {
	log.Info("apiGatewayHTTPController.Status")
	fmt.Fprintf(w, "OK")
}

func (s apiGatewayHTTPController) Swagger(w http.ResponseWriter, r *http.Request) {
	log.Info("apiGatewayHTTPController.Swagger")
	w.Header().Set("Content-Type", "application/json")
	io.Copy(w, strings.NewReader(pb.Swagger))
}

func (s apiGatewayHTTPController) Version(w http.ResponseWriter, r *http.Request) {
	log.Info("apiGatewayHTTPController.Version")
	v := pb.VersionResponse{
		Name:    name,
		Version: version,
	}
	output, err := json.Marshal(v)
	if err != nil {
		http.Error(w, err.Error(), 500)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.Write(output)
}
