// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pb/api-gateway.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	pb/api-gateway.proto

It has these top-level messages:
	EmptyMessage
	VersionResponse
	ServiceStatus
	ServicesStatusList
	EchoRequest
	EchoResponse
*/
package pb

import proto "github.com/gogo/protobuf/proto"
import golang_proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "github.com/mwitkow/go-proto-validators"
import _ "github.com/gomeet/go-proto-gomeetfaker"
import _ "github.com/gogo/protobuf/gogoproto"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ServiceStatus_Status int32

const (
	ServiceStatus_OK          ServiceStatus_Status = 0
	ServiceStatus_UNAVAILABLE ServiceStatus_Status = 1
)

var ServiceStatus_Status_name = map[int32]string{
	0: "OK",
	1: "UNAVAILABLE",
}
var ServiceStatus_Status_value = map[string]int32{
	"OK":          0,
	"UNAVAILABLE": 1,
}

func (x ServiceStatus_Status) String() string {
	return proto.EnumName(ServiceStatus_Status_name, int32(x))
}
func (ServiceStatus_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorApiGateway, []int{2, 0}
}

type EmptyMessage struct {
}

func (m *EmptyMessage) Reset()                    { *m = EmptyMessage{} }
func (m *EmptyMessage) String() string            { return proto.CompactTextString(m) }
func (*EmptyMessage) ProtoMessage()               {}
func (*EmptyMessage) Descriptor() ([]byte, []int) { return fileDescriptorApiGateway, []int{0} }

// VersionMessage represents a version message
type VersionResponse struct {
	// Id represents the message identifier.
	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (m *VersionResponse) Reset()                    { *m = VersionResponse{} }
func (m *VersionResponse) String() string            { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()               {}
func (*VersionResponse) Descriptor() ([]byte, []int) { return fileDescriptorApiGateway, []int{1} }

func (m *VersionResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

// SeviceStatus represents a sub services status message
type ServiceStatus struct {
	Name    string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version string               `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Status  ServiceStatus_Status `protobuf:"varint,3,opt,name=status,proto3,enum=grpc.gomeetexamples.apigateway.ServiceStatus_Status" json:"status,omitempty"`
	EMsg    string               `protobuf:"bytes,4,opt,name=e_msg,json=eMsg,proto3" json:"e_msg,omitempty"`
}

func (m *ServiceStatus) Reset()                    { *m = ServiceStatus{} }
func (m *ServiceStatus) String() string            { return proto.CompactTextString(m) }
func (*ServiceStatus) ProtoMessage()               {}
func (*ServiceStatus) Descriptor() ([]byte, []int) { return fileDescriptorApiGateway, []int{2} }

func (m *ServiceStatus) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServiceStatus) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ServiceStatus) GetStatus() ServiceStatus_Status {
	if m != nil {
		return m.Status
	}
	return ServiceStatus_OK
}

func (m *ServiceStatus) GetEMsg() string {
	if m != nil {
		return m.EMsg
	}
	return ""
}

// ServicesStatusList is the sub services status list
type ServicesStatusList struct {
	Services []*ServiceStatus `protobuf:"bytes,1,rep,name=services" json:"services,omitempty"`
}

func (m *ServicesStatusList) Reset()                    { *m = ServicesStatusList{} }
func (m *ServicesStatusList) String() string            { return proto.CompactTextString(m) }
func (*ServicesStatusList) ProtoMessage()               {}
func (*ServicesStatusList) Descriptor() ([]byte, []int) { return fileDescriptorApiGateway, []int{3} }

func (m *ServicesStatusList) GetServices() []*ServiceStatus {
	if m != nil {
		return m.Services
	}
	return nil
}

// EchoRequest represents a simple message sent to the Echo service.
type EchoRequest struct {
	Uuid    string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *EchoRequest) Reset()                    { *m = EchoRequest{} }
func (m *EchoRequest) String() string            { return proto.CompactTextString(m) }
func (*EchoRequest) ProtoMessage()               {}
func (*EchoRequest) Descriptor() ([]byte, []int) { return fileDescriptorApiGateway, []int{4} }

func (m *EchoRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *EchoRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// EchoResponse represents a simple message that the Echo service return.
type EchoResponse struct {
	Uuid    string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *EchoResponse) Reset()                    { *m = EchoResponse{} }
func (m *EchoResponse) String() string            { return proto.CompactTextString(m) }
func (*EchoResponse) ProtoMessage()               {}
func (*EchoResponse) Descriptor() ([]byte, []int) { return fileDescriptorApiGateway, []int{5} }

func (m *EchoResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *EchoResponse) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*EmptyMessage)(nil), "grpc.gomeetexamples.apigateway.EmptyMessage")
	golang_proto.RegisterType((*EmptyMessage)(nil), "grpc.gomeetexamples.apigateway.EmptyMessage")
	proto.RegisterType((*VersionResponse)(nil), "grpc.gomeetexamples.apigateway.VersionResponse")
	golang_proto.RegisterType((*VersionResponse)(nil), "grpc.gomeetexamples.apigateway.VersionResponse")
	proto.RegisterType((*ServiceStatus)(nil), "grpc.gomeetexamples.apigateway.ServiceStatus")
	golang_proto.RegisterType((*ServiceStatus)(nil), "grpc.gomeetexamples.apigateway.ServiceStatus")
	proto.RegisterType((*ServicesStatusList)(nil), "grpc.gomeetexamples.apigateway.ServicesStatusList")
	golang_proto.RegisterType((*ServicesStatusList)(nil), "grpc.gomeetexamples.apigateway.ServicesStatusList")
	proto.RegisterType((*EchoRequest)(nil), "grpc.gomeetexamples.apigateway.EchoRequest")
	golang_proto.RegisterType((*EchoRequest)(nil), "grpc.gomeetexamples.apigateway.EchoRequest")
	proto.RegisterType((*EchoResponse)(nil), "grpc.gomeetexamples.apigateway.EchoResponse")
	golang_proto.RegisterType((*EchoResponse)(nil), "grpc.gomeetexamples.apigateway.EchoResponse")
	proto.RegisterEnum("grpc.gomeetexamples.apigateway.ServiceStatus_Status", ServiceStatus_Status_name, ServiceStatus_Status_value)
	golang_proto.RegisterEnum("grpc.gomeetexamples.apigateway.ServiceStatus_Status", ServiceStatus_Status_name, ServiceStatus_Status_value)
}
func (this *EmptyMessage) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*EmptyMessage)
	if !ok {
		that2, ok := that.(EmptyMessage)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	return true
}
func (this *VersionResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*VersionResponse)
	if !ok {
		that2, ok := that.(VersionResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Version != that1.Version {
		return false
	}
	return true
}
func (this *ServiceStatus) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ServiceStatus)
	if !ok {
		that2, ok := that.(ServiceStatus)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Version != that1.Version {
		return false
	}
	if this.Status != that1.Status {
		return false
	}
	if this.EMsg != that1.EMsg {
		return false
	}
	return true
}
func (this *ServicesStatusList) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ServicesStatusList)
	if !ok {
		that2, ok := that.(ServicesStatusList)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Services) != len(that1.Services) {
		return false
	}
	for i := range this.Services {
		if !this.Services[i].Equal(that1.Services[i]) {
			return false
		}
	}
	return true
}
func (this *EchoRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*EchoRequest)
	if !ok {
		that2, ok := that.(EchoRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Uuid != that1.Uuid {
		return false
	}
	if this.Content != that1.Content {
		return false
	}
	return true
}
func (this *EchoResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*EchoResponse)
	if !ok {
		that2, ok := that.(EchoResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Uuid != that1.Uuid {
		return false
	}
	if this.Content != that1.Content {
		return false
	}
	return true
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ApiGateway service

type ApiGatewayClient interface {
	// Version method receives no paramaters and returns a version message.
	Version(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*VersionResponse, error)
	// ServicesStatus method receives no paramaters and returns all services status message
	ServicesStatus(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*ServicesStatusList, error)
	// Echo method receives a simple message and returns it.
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
}

type apiGatewayClient struct {
	cc *grpc.ClientConn
}

func NewApiGatewayClient(cc *grpc.ClientConn) ApiGatewayClient {
	return &apiGatewayClient{cc}
}

func (c *apiGatewayClient) Version(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := grpc.Invoke(ctx, "/grpc.gomeetexamples.apigateway.ApiGateway/Version", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiGatewayClient) ServicesStatus(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*ServicesStatusList, error) {
	out := new(ServicesStatusList)
	err := grpc.Invoke(ctx, "/grpc.gomeetexamples.apigateway.ApiGateway/ServicesStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiGatewayClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	out := new(EchoResponse)
	err := grpc.Invoke(ctx, "/grpc.gomeetexamples.apigateway.ApiGateway/Echo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ApiGateway service

type ApiGatewayServer interface {
	// Version method receives no paramaters and returns a version message.
	Version(context.Context, *EmptyMessage) (*VersionResponse, error)
	// ServicesStatus method receives no paramaters and returns all services status message
	ServicesStatus(context.Context, *EmptyMessage) (*ServicesStatusList, error)
	// Echo method receives a simple message and returns it.
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
}

func RegisterApiGatewayServer(s *grpc.Server, srv ApiGatewayServer) {
	s.RegisterService(&_ApiGateway_serviceDesc, srv)
}

func _ApiGateway_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiGatewayServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gomeetexamples.apigateway.ApiGateway/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiGatewayServer).Version(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiGateway_ServicesStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiGatewayServer).ServicesStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gomeetexamples.apigateway.ApiGateway/ServicesStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiGatewayServer).ServicesStatus(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiGateway_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiGatewayServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.gomeetexamples.apigateway.ApiGateway/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiGatewayServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ApiGateway_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.gomeetexamples.apigateway.ApiGateway",
	HandlerType: (*ApiGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _ApiGateway_Version_Handler,
		},
		{
			MethodName: "ServicesStatus",
			Handler:    _ApiGateway_ServicesStatus_Handler,
		},
		{
			MethodName: "Echo",
			Handler:    _ApiGateway_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/api-gateway.proto",
}

func NewPopulatedEmptyMessage(r randyApiGateway, easy bool) *EmptyMessage {
	this := &EmptyMessage{}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedVersionResponse(r randyApiGateway, easy bool) *VersionResponse {
	this := &VersionResponse{}
	this.Name = string(randStringApiGateway(r))
	this.Version = string(randStringApiGateway(r))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedServiceStatus(r randyApiGateway, easy bool) *ServiceStatus {
	this := &ServiceStatus{}
	this.Name = string(randStringApiGateway(r))
	this.Version = string(randStringApiGateway(r))
	this.Status = ServiceStatus_Status([]int32{0, 1}[r.Intn(2)])
	this.EMsg = string(randStringApiGateway(r))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedServicesStatusList(r randyApiGateway, easy bool) *ServicesStatusList {
	this := &ServicesStatusList{}
	if r.Intn(10) != 0 {
		v1 := r.Intn(5)
		this.Services = make([]*ServiceStatus, v1)
		for i := 0; i < v1; i++ {
			this.Services[i] = NewPopulatedServiceStatus(r, easy)
		}
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedEchoRequest(r randyApiGateway, easy bool) *EchoRequest {
	this := &EchoRequest{}
	this.Uuid = string(randStringApiGateway(r))
	this.Content = string(randStringApiGateway(r))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedEchoResponse(r randyApiGateway, easy bool) *EchoResponse {
	this := &EchoResponse{}
	this.Uuid = string(randStringApiGateway(r))
	this.Content = string(randStringApiGateway(r))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

type randyApiGateway interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneApiGateway(r randyApiGateway) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringApiGateway(r randyApiGateway) string {
	v2 := r.Intn(100)
	tmps := make([]rune, v2)
	for i := 0; i < v2; i++ {
		tmps[i] = randUTF8RuneApiGateway(r)
	}
	return string(tmps)
}
func randUnrecognizedApiGateway(r randyApiGateway, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldApiGateway(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldApiGateway(dAtA []byte, r randyApiGateway, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateApiGateway(dAtA, uint64(key))
		v3 := r.Int63()
		if r.Intn(2) == 0 {
			v3 *= -1
		}
		dAtA = encodeVarintPopulateApiGateway(dAtA, uint64(v3))
	case 1:
		dAtA = encodeVarintPopulateApiGateway(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateApiGateway(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateApiGateway(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateApiGateway(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulateApiGateway(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}

func init() { proto.RegisterFile("pb/api-gateway.proto", fileDescriptorApiGateway) }
func init() { golang_proto.RegisterFile("pb/api-gateway.proto", fileDescriptorApiGateway) }

var fileDescriptorApiGateway = []byte{
	// 616 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x41, 0x4f, 0x13, 0x4f,
	0x14, 0xff, 0xcf, 0x76, 0xd9, 0xc2, 0x83, 0x3f, 0xe0, 0xc4, 0x84, 0xda, 0x90, 0x5a, 0xd7, 0x0b,
	0x41, 0x76, 0x47, 0x2a, 0x31, 0x46, 0x4f, 0x6d, 0x42, 0x08, 0xb1, 0x28, 0xd9, 0x46, 0x0e, 0x5e,
	0xc8, 0x74, 0x19, 0x96, 0x0d, 0xec, 0xce, 0xda, 0x99, 0x16, 0xf1, 0x26, 0x5f, 0x81, 0x6f, 0xc0,
	0xc9, 0x43, 0x3f, 0x00, 0x47, 0xcf, 0xbd, 0xfa, 0x05, 0x14, 0xfd, 0x10, 0x1e, 0x0d, 0xb3, 0xb3,
	0xb0, 0xd5, 0x84, 0x42, 0xf4, 0xb4, 0x33, 0x6f, 0x7e, 0xbf, 0x37, 0xbf, 0x79, 0xbf, 0xb7, 0x0f,
	0xee, 0x26, 0x6d, 0x42, 0x93, 0xd0, 0x09, 0xa8, 0x64, 0x87, 0xf4, 0xc8, 0x4d, 0x3a, 0x5c, 0x72,
	0x5c, 0x09, 0x3a, 0x89, 0xef, 0x06, 0x3c, 0x62, 0x4c, 0xb2, 0xf7, 0x34, 0x4a, 0x0e, 0x98, 0x70,
	0x69, 0x12, 0x6a, 0x54, 0x79, 0x3e, 0xe0, 0x3c, 0x38, 0x60, 0x17, 0x4c, 0x42, 0xe3, 0x98, 0x4b,
	0x2a, 0x43, 0x1e, 0x8b, 0x94, 0x5d, 0x7e, 0x1a, 0x84, 0x72, 0xaf, 0xdb, 0x76, 0x7d, 0x1e, 0x91,
	0xe8, 0x30, 0x94, 0xfb, 0xfc, 0x90, 0x04, 0xdc, 0x51, 0x87, 0x4e, 0x8f, 0x1e, 0x84, 0x3b, 0x54,
	0xf2, 0x8e, 0x20, 0x97, 0x4b, 0xcd, 0x7b, 0x96, 0xe3, 0xa5, 0x77, 0x5f, 0xd1, 0xd2, 0xfd, 0x2e,
	0xdd, 0x67, 0x1d, 0x92, 0x5b, 0x6b, 0xa6, 0x33, 0xc4, 0x0c, 0x38, 0x51, 0xe1, 0x76, 0x77, 0x57,
	0xed, 0xd4, 0x46, 0xad, 0x52, 0xb8, 0x3d, 0x0d, 0x53, 0xab, 0x51, 0x22, 0x8f, 0x36, 0x98, 0x10,
	0x34, 0x60, 0x76, 0x0b, 0x66, 0xb6, 0x58, 0x47, 0x84, 0x3c, 0xf6, 0x98, 0x48, 0x78, 0x2c, 0x18,
	0x9e, 0x07, 0x33, 0xa6, 0x11, 0x2b, 0xa1, 0x2a, 0x5a, 0x98, 0x68, 0x8c, 0x0f, 0xfa, 0x96, 0xb9,
	0x68, 0xcc, 0x22, 0x4f, 0x45, 0xb1, 0x0d, 0xc5, 0x5e, 0x4a, 0x28, 0x19, 0x79, 0x40, 0x09, 0x79,
	0xd9, 0x81, 0xfd, 0x15, 0xc1, 0xff, 0x2d, 0xd6, 0xe9, 0x85, 0x3e, 0x6b, 0x49, 0x2a, 0xbb, 0xe2,
	0xef, 0x73, 0xe2, 0x26, 0x58, 0x42, 0xe5, 0x2a, 0x15, 0xaa, 0x68, 0x61, 0xba, 0xb6, 0xe2, 0x5e,
	0x6f, 0x94, 0x3b, 0x24, 0xc0, 0x4d, 0x3f, 0x9e, 0xce, 0x81, 0xe7, 0x61, 0x8c, 0x6d, 0x47, 0x22,
	0x28, 0x99, 0xea, 0xbe, 0xe2, 0xa0, 0x6f, 0x15, 0xce, 0x10, 0xf2, 0x4c, 0xb6, 0x21, 0x02, 0xfb,
	0x01, 0x58, 0x5a, 0xb7, 0x05, 0xc6, 0xeb, 0x97, 0xb3, 0xff, 0xe1, 0x19, 0x98, 0x7c, 0xf3, 0xaa,
	0xbe, 0x55, 0x5f, 0x6f, 0xd6, 0x1b, 0xcd, 0xd5, 0x59, 0x64, 0x6f, 0x03, 0xd6, 0x17, 0x88, 0x14,
	0xda, 0x0c, 0x85, 0xc4, 0xeb, 0x30, 0x2e, 0x74, 0xb4, 0x84, 0xaa, 0x85, 0x85, 0xc9, 0x9a, 0x73,
	0x2b, 0x99, 0xde, 0x25, 0xdd, 0xf6, 0x60, 0x72, 0xd5, 0xdf, 0xe3, 0x1e, 0x7b, 0xd7, 0x65, 0x42,
	0xe2, 0x0a, 0x98, 0xdd, 0x6e, 0xb8, 0xa3, 0x0b, 0x08, 0x83, 0xbe, 0x65, 0x61, 0x13, 0x1b, 0x5b,
	0x2b, 0x9e, 0x8a, 0xe3, 0x87, 0x50, 0xf4, 0x79, 0x2c, 0x59, 0x2c, 0x75, 0x09, 0x27, 0x06, 0x7d,
	0x6b, 0xec, 0x18, 0x19, 0x9b, 0xc8, 0xcb, 0x4e, 0xec, 0x16, 0x4c, 0xa5, 0x39, 0xb5, 0xd3, 0xff,
	0x22, 0x69, 0xed, 0xb4, 0x00, 0x50, 0x4f, 0xc2, 0xb5, 0xf4, 0x3d, 0xf8, 0x23, 0x82, 0xa2, 0xee,
	0x28, 0xbc, 0x34, 0xea, 0xf1, 0xf9, 0x56, 0x2c, 0x93, 0x51, 0xe8, 0xdf, 0x1a, 0xd5, 0x9e, 0x3b,
	0xfe, 0xf2, 0xe3, 0xc4, 0xb8, 0x83, 0x67, 0xd4, 0xcf, 0xd8, 0x5b, 0x26, 0x59, 0xaf, 0x9c, 0x20,
	0x98, 0x1e, 0x76, 0xe7, 0x96, 0x52, 0x6a, 0x37, 0x74, 0x2d, 0xe7, 0xbd, 0x7d, 0x5f, 0xa9, 0xb9,
	0x87, 0xe7, 0x32, 0x35, 0x99, 0x95, 0x44, 0xf7, 0xdc, 0x07, 0x30, 0x2f, 0xaa, 0x8f, 0x1f, 0x8d,
	0x94, 0x72, 0xe5, 0x7b, 0x79, 0xe9, 0x66, 0xe0, 0xe1, 0x8a, 0xd8, 0x53, 0x99, 0x06, 0xe6, 0xef,
	0xf1, 0xe7, 0x68, 0xb1, 0xb1, 0xff, 0xf3, 0x5b, 0x05, 0x7d, 0x3a, 0xaf, 0xa0, 0xb3, 0xf3, 0x0a,
	0xfa, 0xfc, 0xbd, 0x82, 0xa0, 0xea, 0xf3, 0xe8, 0x9a, 0xb4, 0xbd, 0xe5, 0xb7, 0x8f, 0xff, 0x98,
	0x49, 0x4e, 0x86, 0x24, 0xa2, 0xe7, 0x3b, 0xb9, 0xd9, 0x49, 0x92, 0xf6, 0x8b, 0xa4, 0x7d, 0x6a,
	0x98, 0x6b, 0x1b, 0x9b, 0x8d, 0xb6, 0xa5, 0x46, 0xcd, 0x93, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xb4, 0xc7, 0x12, 0x4d, 0x61, 0x05, 0x00, 0x00,
}
